---
title: "STSCI5160 - Prelim 2"
author: "Ryan Zhou"
date: "2023-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Analyze
```{r}
# Load the CSV file
data <- read.csv("/Users/ryanzhou/Documents/Study/Cornell/2023/Course/STSCI 5160/Prelim/STSCI-4110-5160-Prelim2/Handout/final_cardiac_data.csv")

# Data Overview
head(data)
str(data)

# Find all NA value
data[!complete.cases(data), ]

# Find column with NA
columns_with_na <- colSums(is.na(data)) > 0; columns_with_na
```

Quesiton 1:
how to deal with all those missing value

```{r}
hist(data$gender)
hist(data$age)
hist(data$ethnic1)
hist(data$educ)
hist(data$sleep.hrs)
hist(data$diabetes)
hist(data$smoker)
hist(data$bmi)
```

```{r}
# Analyz the smoker data individual
smoker_data <- data$smoker
# Tell the percentage for each category
table(smoker_data, useNA = "ifany")
# It's not a good idea to drop the columns with NA, since it takes almost 10% of data. According to the handout, we have another category, called "9-Don't Know", which is exactly the meaning of NA in this column.
smoker_data[is.na(smoker_data)] <- 9
```

```{r}
length(unique(data$seqn))
length(unique(data$X))
length(unique(rownames(data)))
```

```{r}
# Remove all na value, and find the relation between each variable
data <- data[, !(names(data) %in% c("X", "seqn"))]
data_no_na <- na.omit(data)
cor_matrix <- cor(data_no_na)
heatmap(cor_matrix)
pairs(data_no_na)
```

```{r}
# smoker modle fitting
data$smoker[data$smoker == 2] <- 0
# 1. 使用没有 NA 的数据来训练模型
model <- glm(smoker ~ gender + educ + age, data = na.omit(data), family = binomial)

# 2. 在包含 NA 的数据上进行预测
data_with_na <- data
data_with_na$predicted_smoker <- predict(model, newdata = data_with_na, type = "response")

# 3. 将预测概率转换为二分类结果
data_with_na$predicted_smoker <- ifelse(data_with_na$predicted_smoker >= 0.5, 1, 0)

# 4. 将有 NA 的数据中 'smoker' 列的值替换为预测值
data_with_na$smoker[is.na(data_with_na$smoker)] <- data_with_na$predicted_smoker[is.na(data_with_na$smoker)]

# 检查匹配的行数
matching_rows <- sum(data_with_na$smoker == data$smoker, na.rm = TRUE)

# 计算匹配的比例
match_ratio <- matching_rows / nrow(data)

cat("Match Ratio:", match_ratio, "\n")

```

